### ISSUE TITLE
Staff link not working

### ISSUE THREAD

**Issue by Trollcraft1002** [LabsStar/goddess-anime#3]
**Describe the bug**
404(559)

**To Reproduce**
1. Go to 'https://goddessanime.com'
2. Click on 'Staff Members -> View all'
3. Go to 'https://goddessanime.com/staff'

**Expected behavior**
 To open the page with all staff members
**Screenshots**

**Comment by 0xhylia** [comment]
This has been fixed!

https://github.com/LabsStar/goddess-anime/commit/3d70a7cbeab08ba230799b5d9d97924c0505b654
